### ISSUE TITLE
Cannot compile on 4.6

### ISSUE THREAD

**Issue by Arthegal** [iniside/ActionRPGGame#3]
Hi,
i'm unable to compile on 4.6 having the following erros;

error C2039: 'GetSafeNormal2D' : is not a member of 'FVector' FCTHudWidget.cpp  33  1   ActionRPGGame
error C2248: 'UK2Node_SpawnActorFromClass::NodeTooltip' : cannot access private member declared in class 'UK2Node_SpawnActorFromClass' BPNode_CreateEffectField.cpp 37  1   ActionRPGGame
error C2248: 'UK2Node_SpawnActorFromClass::CachedNodeTitle' : BPNode_CreateEffectField.cpp  133 1   ActionRPGGame

Is this project supporting 4.6?
Thanks in advance for your help

**Comment by iniside** [comment]
It will only compile with 4.7 and with some custom changes it.  
Like this one:
https://github.com/EpicGames/UnrealEngine/commit/0210b4c77cb5ec177d4a8b71e395014e64c2a31f

But idk if this is going in released build before 4.8.

**Comment by kuafu** [comment]
I fixed 4.6 compile problem,but Editor crashed on start.
